### ISSUE TITLE
Gradle sync failed

### ISSUE THREAD

**Issue by Zaraki596** [haroldadmin/MovieDB#9]
Can anybody put a decent readme on how to set up the Gradle for others to look at it?

Getting error like this :
ERROR: Could not download gradle.jar (io.fabric.tools:gradle:1.29.0): No cached version available for offline mode

**Comment by haroldadmin** [comment]
Hi.

The error you've reported occurs when Gradle can't download dependencies, or it is set to work-offline.

Maybe refer to this question here? [How to disable offline mode in Gradle?](https://stackoverflow.com/questions/28712025/how-to-disable-gradle-offline-mode-in-android-studio)

**Comment by Zaraki596** [comment]
Ok, I have tried this and fiddle around with it offline and online mode, Didn't seem to work.
Finally, I figured out the problem was that I have a restrictive DNS setup on my machine which causes fabric.io and other domains of it to not load. Finally, I removed fabric domains from the list it begins to work. Sorry didn't get a chance to update the comment the issue.
By the way thanks for such amazing repo @haroldadmin

**Comment by haroldadmin** [comment]
I run pihole on my network, so I ran into this problem too. I'm glad you were able to fix it.

MovieDB is not actively maintained by me any more, so you will find some questionable code in there that needs fixing. 

I'm glad you tried exploring it, though.

**Comment by Zaraki596** [comment]
Thank you, I would be glad to help on fixing those bugs, Where can I start? Or some other repo where I can contribute or learn something from you.

**Comment by haroldadmin** [comment]
MovieDB needs a lot of reworking. 

I built it using a very stripped down version of MvRx (bundled as mvrx-lite module in the project) without having a deep understanding of it. The biggest change that needs to be made is to move the project over to [MvRx](https://GitHub.com/Airbnb/MvRx) or [Vector](https://GitHub.com/haroldadmin/Vector).

The database needs to be rewritten as well, letting go of a lot of needless relations that are in there. Maybe experimenting with SQLDelight would be nice.

I'd also like to move over the repository layer from RxJava to Coroutines and Flow. Perhaps even look into using [Store](https://github.com/dropbox/Store) from Dropbox.

Koin looks fine for DI, not sure if moving to Dagger is necessary.

So yeah, there's a lot of work that needs to be done. You might want to take a look at some of my other repos instead of attempting a rewrite of this app.
